// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBmFZyF-OqBSDJeG_0lXlzSgKbhwAzQHI',
    appId: '1:57739993966:web:27792cfe7d7dcc2df8977f',
    messagingSenderId: '57739993966',
    projectId: 'registration-2e34e',
    authDomain: 'registration-2e34e.firebaseapp.com',
    storageBucket: 'registration-2e34e.firebasestorage.app',
    measurementId: 'G-ZJG01MG2CX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBrMv4RH9Hy50yf9moO3cLXmAu7gHghRw',
    appId: '1:57739993966:android:03c4d54c0342556ef8977f',
    messagingSenderId: '57739993966',
    projectId: 'registration-2e34e',
    storageBucket: 'registration-2e34e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMRr0w-8ArTxwQn8fKSqP5wHQDmaOF4ps',
    appId: '1:57739993966:ios:b559b220ad7d1ea7f8977f',
    messagingSenderId: '57739993966',
    projectId: 'registration-2e34e',
    storageBucket: 'registration-2e34e.firebasestorage.app',
    iosBundleId: 'com.example.registration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMRr0w-8ArTxwQn8fKSqP5wHQDmaOF4ps',
    appId: '1:57739993966:ios:b559b220ad7d1ea7f8977f',
    messagingSenderId: '57739993966',
    projectId: 'registration-2e34e',
    storageBucket: 'registration-2e34e.firebasestorage.app',
    iosBundleId: 'com.example.registration',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBmFZyF-OqBSDJeG_0lXlzSgKbhwAzQHI',
    appId: '1:57739993966:web:476b9d01b29b6ae0f8977f',
    messagingSenderId: '57739993966',
    projectId: 'registration-2e34e',
    authDomain: 'registration-2e34e.firebaseapp.com',
    storageBucket: 'registration-2e34e.firebasestorage.app',
    measurementId: 'G-R9ZVZCDWN0',
  );
}
